todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls'))
]

todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:todo_id>/delete', views.delete, name='delete'),
    path('<int:todo_id>/update', views.update, name='update'),
    path('create', views.create, name='create')
]

todos/models.py
from django.db import models
from django.utils import timezone


class Todo(models.Model):
    todo_text = models.CharField(default="", max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    todo_status = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_text

todos/views.py
from django.http import HttpResponseRedirect
from django.forms import ModelForm
from django.views import generic
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Todo


class IndexView(generic.ListView):
    model = Todo
    template_name = 'todos/index.html'


def delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()

    return HttpResponseRedirect(reverse('todos:index'))


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ('todo_text', 'todo_status')


def create(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('todos:index'))
    else:
        form = TodoForm()

    return render(request, 'todos/create.html', {'form': form})


def update(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('todos:index'))
    else:
        form = TodoForm(instance=todo)

    return render(request, 'todos/update.html', {"form": form})

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet">
    <title>Simple Todo App</title>
</head>
<body>
<h1>This is Simple Todo App</h1>
{% block content %}
{% endblock %}
</body>
</html>

todos/templates/todos/create.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p  }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

todos/templates/todos/detail.html
<h1>{{ todo.todo_text }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

todos/templates/todos/index.html
{% extends 'base.html' %}

{% block content %}
<h1>List of Todo</h1>
<a href="{% url 'todos:create' %}">Create Todo</a>
<div class="todo_list">
    {% for todo in todo_list %}
    <div class="todo">
        <p>{{ todo.todo_text }}</p>
        <div class="todo--button">
            <a href="{% url 'todos:update' todo.id %}">
                <button class="button--update">
                    Update
                </button>
            </a>
            <form action="{% url 'todos:delete' todo.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="button--delete">Delete</button>
            </form>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

todos/templates/todos/update.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}